### ISSUE TITLE
TypeError: 'pickSummaryLanguage' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by nautilus28** [aboSamoor/pycld2#1]
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import pycld2 as cld2
> > > detectedLangName, detectedLangCode, isReliable, textBytesFound, details = cld2.detect("This is my sample text", pickSummaryLanguage=True, removeWeakMatches=False)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: 'pickSummaryLanguage' is an invalid keyword argument for this function

It looks like a bug.

**Comment by aboSamoor** [comment]
can you suggest a pull request?

**Comment by villmow** [comment]
Got the same error...

**Comment by bsolomon1124** [comment]
I think the issue here is that this was never actually a parameter.

The updated README and docstrings reflect this.
