### ISSUE TITLE
Install fails on Centos 7, Python 2.7, setuptools 0.9

### ISSUE THREAD

**Issue by Benbbe** [aboSamoor/pycld2#25]
Hello;

Installation fails on Centos 7 64 bits , gcc 4.8.5 20150623 

`[osboxes@osboxes TripAdvisor-Crawling-Suite]$ python -m pip install -U pycld2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pycld2
  Downloading https://files.pythonhosted.org/packages/21/d2/8b0def84a53c88d0eb27c67b05269fbd16ad68df8c78849e7b5d65e6aec3/pycld2-0.41.tar.gz (41.4MB)
     |████████████████████████████████| 41.4MB 214kB/s 
Installing collected packages: pycld2
    Running setup.py install for pycld2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vHZIha/pycld2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vHZIha/pycld2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-CZQQb3/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-vHZIha/pycld2/
    Complete output (21 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pycld2
    copying pycld2/__init__.py -> build/lib.linux-x86_64-2.7/pycld2
    running build_ext
    building 'pycld2._pycld2' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-vHZIha
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-vHZIha/pycld2
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-vHZIha/pycld2/cld2
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-vHZIha/pycld2/cld2/internal
    creating build/temp.linux-x86_64-2.7/tmp/pip-install-vHZIha/pycld2/bindings
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/tmp/pip-install-vHZIha/pycld2/cld2/internal -I/tmp/pip-install-vHZIha/pycld2/cld2/public -I/usr/include/python2.7 -c /tmp/pip-install-vHZIha/pycld2/cld2/internal/cld2_generated_cjk_compatible.cc -o build/temp.linux-x86_64-2.7/tmp/pip-install-vHZIha/pycld2/cld2/internal/cld2_generated_cjk_compatible.o -w -O2 -m64 -fPIC
    gcc: error trying to exec 'cc1plus': execvp: Aucun fichier ou dossier de ce type
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vHZIha/pycld2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vHZIha/pycld2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-CZQQb3/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
`

**Comment by bsolomon1124** [comment]
@Benbbe what does the following show?

```bash
python -c 'import setuptools; print(setuptools.__version__)'
python -c 'import distutils; print(distutils.__version__)'
```

**Comment by Benbbe** [comment]
@bsolomon1124
Commands results
[osboxes@osboxes ~]$ python -c 'import setuptools; print(setuptools.__version__)'
0.9.8
[osboxes@osboxes ~]$ python -c 'import distutils; print(distutils.__version__)'
2.7.5
[osboxes@osboxes ~]$ python -m pip --version
pip 19.3.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)

**Comment by bsolomon1124** [comment]
Okay, so firstly I suspect that `python -m pip install --upgrade setuptools` may help.  The traceback takes issue with `long_description_content_type`, which is a recently-added option.

If that doesn't help, we may need to check the `setuptools` version in `pycld2/setup.py`.  From your traceback, it's actually distutils that raises (https://github.com/python/cpython/blob/9f94e52e8d38092520a3bfb1bf1ef9cbb0836584/Lib/distutils/dist.py#L255), but setuptools is just a gateway to distutils.

**Comment by bsolomon1124** [comment]
For what its worth, a Python 2 pycld2 install works on OS X + setuptools 41.6.0:

```
python -m pip install pycld2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pycld2
  Downloading https://files.pythonhosted.org/packages/21/d2/8b0def84a53c88d0eb27c67b05269fbd16ad68df8c78849e7b5d65e6aec3/pycld2-0.41.tar.gz (41.4MB)
     |████████████████████████████████| 41.4MB 16.3MB/s 
Building wheels for collected packages: pycld2
  Building wheel for pycld2 (setup.py) ... done
  Created wheel for pycld2: filename=pycld2-0.41-cp27-cp27m-macosx_10_13_x86_64.whl size=4776236 sha256=67dcc1718160a8b9840098898d9af5549f04900f48401d7f4c544b0e1119ebc9
  Stored in directory: /Users/bradsolomon/Library/Caches/pip/wheels/c6/8f/e9/08a1a8932a490175bd140206cd86a3dbcfc70498100de11079
Successfully built pycld2
Installing collected packages: pycld2
Successfully installed pycld2-0.41
```

**Comment by Benbbe** [comment]
@bsolomon1124 It's OK now.
It builds correctly after updating install tools

**Comment by justinw-SMC** [comment]
Hello, I'm still having the same issue and tried the solutions posted above:
```
[root@localhost ~]# python -c 'import setuptools; print(setuptools.__version__)'
0.9.8
[root@localhost ~]# python -c 'import distutils; print(distutils.__version__)'
2.7.5
[root@localhost ~]# python -m pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
[root@localhost ~]# python -m pip install --upgrade setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/dc/73/88920663229023b724a854d1ab7e3e50a1a28b63eeec399a604ba30f9242/setuptools-62.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.py", line 8, in <module>
        import _distutils_hack.override  # noqa: F401
      File "_distutils_hack/__init__.py", line 194
        f'spec_for_{name}',
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eP5IyL/setuptools/
You are using pip version 8.1.2, however version 22.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@localhost ~]# python -m pip install --upgrade --user setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/dc/73/88920663229023b724a854d1ab7e3e50a1a28b63eeec399a604ba30f9242/setuptools-62.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.py", line 8, in <module>
        import _distutils_hack.override  # noqa: F401
      File "_distutils_hack/__init__.py", line 194
        f'spec_for_{name}',
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TWudji/setuptools/
You are using pip version 8.1.2, however version 22.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Here are the details on my OS
```
[root@localhost ~]# cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by IgorStanishevskiy** [comment]
Try this:

pip install --upgrade pip==9.0.3
pip install --upgrade setuptools 

It should work.

**Comment by justinw-SMC** [comment]
Worked like a charm! Thank you!
```
[root@localhost dmi]# python -c 'import setuptools; print(setuptools.__version__)'
0.9.8
[root@localhost dmi]# python -c 'import distutils; print(distutils.__version__)'
2.7.5
[root@localhost dmi]# python -m pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
[root@localhost dmi]# python -m pip install --upgrade pip==9.0.3
Collecting pip==9.0.3
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.1MB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.3
You are using pip version 9.0.3, however version 22.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@localhost dmi]# python -m pip install --upgrade setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/e1/b7/182161210a13158cd3ccc41ee19aadef54496b74f2817cc147006ec932b4/setuptools-44.1.1-py2.py3-none-any.whl (583kB)
    100% |████████████████████████████████| 583kB 2.1MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools-0.9.8:
      Successfully uninstalled setuptools-0.9.8
Successfully installed setuptools-44.1.1
You are using pip version 9.0.3, however version 22.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@localhost dmi]# python -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 1.0MB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-20.3.4
You are using pip version 20.3.4, however version 22.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Also, I've been using another workaround for those still working in CentOS 7:
[How to install Python 3 on Red Hat Enterprise Linux](https://developers.redhat.com/blog/2018/08/13/install-python3-rhel)
```
yum install rh-python36
scl enable rh-python36 bash
```
Thanks!
