### ISSUE TITLE
Error on Windows: fatal error C1083: Cannot open include file: 'strings.h': No such file or directory

### ISSUE THREAD

**Issue by NagiReddyPadala** [aboSamoor/pycld2#7]
While building the package pycld2 on Windows using the command "python setup.py build", getting the error "bindings\pycldmodule.cc(16) : fatal error C1083: Cannot open include file: 'strings.h': No such file or directory".

**Comment by steftux** [comment]
I get the same error. :-/

**Comment by bsolomon1124** [comment]
@NagiReddyPadala  @steftux  Should be fixed via c5e84d6 and 94a589d; please let us know if this is still an issue and we can reopen. (Note that the dev version is not as of right now on PyPI.)
